name       : python-nest-asyncio
version    : 1.5.5
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/n/nest_asyncio/nest_asyncio-1.5.5.tar.gz : e442291cd942698be619823a17a86a5759eabe1f8613084790de189fe9e16d65
homepage   : https://github.com/erdewit/nest_asyncio
license    : BSD-2-Clause
component  : programming.python
summary    : Patch asyncio to allow nested event loops
description: |
    Patch asyncio to allow nested event loops.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
