name       : python-nest-asyncio
version    : 1.5.6
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/n/nest_asyncio/nest_asyncio-1.5.6.tar.gz : d267cc1ff794403f7df692964d1d2a3fa9418ffea2a3f6859a439ff482fef290
homepage   : https://github.com/erdewit/nest_asyncio
license    : BSD-2-Clause
component  : programming.python
summary    : Patch asyncio to allow nested event loops
description: |
    Patch asyncio to allow nested event loops.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
