name       : python-nest-asyncio
version    : 1.5.4
release    : 2
source     :
    - https://github.com/erdewit/nest_asyncio/archive/refs/tags/v1.5.4.tar.gz : 783198b39e0feeb8ef2c059e1932c7bb203efa410b8de1012a159c7a54adb9de
homepage   : https://github.com/erdewit/nest_asyncio
license    : BSD-2-Clause
component  : programming.python
summary    : Patch asyncio to allow nested event loops
description: |
    Patch asyncio to allow nested event loops.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
